"""
Email Settings
--------------
Stores email configuration
for automated reporting.
"""
from dotenv import load_dotenv
import os

load_dotenv()
# -----------------------------------------
# Gmail Account
# -----------------------------------------

EMAIL_SENDER = os.getenv("EMAIL_SENDER")

EMAIL_RECEIVER = os.getenv("EMAIL_RECEIVER")

# -----------------------------------------
# Gmail App Password
# -----------------------------------------
# Paste the App Password
# generated by Google.

EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")

# -----------------------------------------
# SMTP Settings
# -----------------------------------------

SMTP_SERVER = "smtp.gmail.com"

SMTP_PORT = 587
